using UnityEngine;

public enum Creadores
{
    Alejandro_Marchena,
    Acieff_Valentin,
    Carreras_Lopez_Benjamin,
    Castro_Corradi_Maximiliano,
    Corro_Benicio,
    Cruceño_Fratti_Lucas,
    Dalmau_Ulises,
    Diaz_Corvalan_Matias_Federico,
    Echavarria_Lander,
    Emili_Bruno,
    Errecalde_Naiara,
    Fuentes_Barraquero_Tomás,
    Gongora_Rosi_Iñaki,
    Gonzalez_Pelaitai_Facundo,
    Llamas_Facundo_Mariano,
    Maldonado_Ignacio_Sebastián,
    Manitta_Mazzaresi_Lucio,
    Marthi_Santiago,
    Paez_Delgadillo_Nicolas,
    Pagano_Guiñazú_Federico,
    Rada_Lizarraga_Lucas,
    Romito_Nazar_Juan_Martín,
    Sabatini_Cialone_Santino,
    Schugurensky_Ivo,
    Varaschin_Emilio,
}
